Attach changelog to release automatically
woocommerce/automations pull request #49
Opened 2021-12-02 13:51 UTC by gigitux

This PR fixes woocommerce/woocommerce-gutenberg-products-block#4636

## Manual test

1. Create a new repo. You can start from [this template](https://github.com/gigitux/woocommerce-automation-test-repo).
2. Add a secret named `GITHUB_TOKEN` with a Github token with `repo` permission enabled.
2. Set a workflow for `woocoomerce-automation`. You can copy-paste [this file](https://github.com/gigitux/woocommerce-automation-test-repo/blob/main/.github/workflows/automation.yml). The important thing is to change the value `uses`. It has to point to this branch.
3. Create a new milestone and give the title a number version (eg: 1.0.0).
4. Create a PR with a changelog, assign the milestone created, and merge it ([example](https://github.com/gigitux/woocommerce-automation-test-repo/pull/36)).
5. Create a release with Github UI.
6. Now, create a new branch with this structure `release/{number_version}` (eg: 1.0.0) and push it.

Now the GitHub actions should be:
* create a new PR for the release.
* edit the description of the last release and add the changelog.

2021-12-03 14:58 UTC, nerrad requested changes
I think there may be a misunderstanding of what goal we're shooting for here.

The release automation currently in this project is mostly just creating an opinionated "release Pull Request" triggered by the creation of a branch for handling a release build. At the point of this release PR being created, there won't necessarily be any corresponding GitHub release branch for the PR (in the case of WooCommerce Blocks, the GH release is triggered by a script executed by whoever is doing the release, later in the process).

So as is, this PR doesn't solve the issue because it will end up adding the changelog to the _previous_ release (not the one being worked on).

One thing you could investigate is whether you could have an automation triggered on the [`releaseevent`](https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#releaseevent) - hopefully you could get enough information from that payload to generate and attach the changelog?

2021-12-03 14:58 UTC, nerrad commented on lib/automations/release/branch-create-handler.js
> +		await attachChangelogToRelease( context, octokit, changelog );
The GitHub release won't have been created yet by this point right? Won't this just attach this to the previous release?

2022-04-04 09:48 UTC, alexflorisca approved these changes
Good work @gigitux. The only thing I'd say is that this action looks for a specific format in our Woo Blocks Release PRs, which might not apply to Woo core or other Woo products. I'm happy for us to leave it as is though because other teams can choose to use it or not. If we give it a more specific name, then other teams start using it, it won't be very clear. 

Merge it and let's try it out on the next Woo Blocks release 👍

2022-04-04 10:52 UTC, gigitux commented
> The only thing I'd say is that this action looks for a specific format in our Woo Blocks Release PRs, which might not apply to Woo core or other Woo products.

The specific format that we use in our Woo Blocks Release PRs is generated automatically by this automation repo (from the creation of the PR to the creation of the release). I guess that the format is always the same if a team adopts this automation.

2022-05-13 14:50 UTC, merged